### PR TITLE
chore(sdk): Create workflow for publishing SDK JAR to GH packages

### PR DESCRIPTION
**Pull request by drew-patel**
# Description

Publish SDK as a JAR in Github Packages used for running tests on `three-id`.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Run workflow on PR before merge

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings

### Published to our maven registry
Screen Shot 2022-05-24 at 20 51 27

### CODE REVIEW

**Comment by crimeminister** [comment]
@drew-patel Does this need to wait on changes to the package repository configuration?

**Comment by drew-patel** [comment]
> @drew-patel Does this need to wait on changes to the package repository configuration?

Yes. I have the key now. Going to change some stuff and sign the JAR

**Comment by drew-patel** [comment]
> @drew-patel Does this need to wait on changes to the package repository configuration?

Currently blocked on this error during the run: 
```pg: signing failed: Inappropriate ioctl for device```

I need to modify the `settings.xml` or `pom.xml` which is annoying and maybe install `maven-gpg-plugin`. Not a straightforward way to do this with `lein`.

These are the instructions. Just need a clean way to do it on Github Actions.

Please make sure that the maven-gpg-plugin is configured to prevent gpg from using PIN entry programs, as follows:
```
<configuration>
  <gpgArguments>
      <arg>--pinentry-mode</arg>
      <arg>loopback</arg>
  </gpgArguments>
</configuration>
```

**Comment by drew-patel** [comment]
Going to close this since the gpg signing via GH actions is annoying and will rely on publishing manually for the time being.

**Pull request closed without merging**
